import { Link } from "react-router-dom";
import CorporatePageFrame from "@/components/CorporatePageFrame";
import aboutImage from "@/assets/img-20250827-wa0020-1.jpg";

const focus = [["01", "Peak performance", "Unlock human potential"], ["02", "Productivity", "Achieve organisational goals"], ["03", "Profitability", "Drive business success"], ["04", "Excellence", "Maintain the highest standards"]];
const values = [["Excellence", "We maintain the highest standards in everything we do, ensuring our graduates receive world-class training."], ["Integrity", "We operate with honesty, transparency, and ethical practices in all our interactions."], ["Empowerment", "We believe in unlocking human potential and empowering individuals to achieve their dreams."], ["Innovation", "We continuously evolve our methods and approaches to stay at the forefront of coaching education."], ["Impact", "We measure our success by the positive transformation we create in the lives of our students."], ["Recognition", "We celebrate achievements and recognise the hard work and dedication of our community."]];

const About = () => (
  <CorporatePageFrame pageNumber="02" eyebrow="About Kingshill" title={<>The school of <em>discovery.</em></>} intro="Kingshill Coaching Academy is a Human Capital Development and Intelligence Consulting organisation providing training services with relevant insights to help people and organisations move forward." heroImage={aboutImage} heroAlt="Kingshill professionals gathered for a learning session" heroCaption="Human capital development · Lagos">
    <section className="kh-cp-section kh-cp-section--paper"><div className="kh-cp-shell"><div className="kh-cp-section__head kh-cp-reveal"><div className="kh-cp-section__label"><span>01</span><span>Our point of view</span></div><div><h2>Potential is a practice.</h2><p>We are Nigeria&apos;s first registered coaching academy, providing Human Capital Development services with the most recent tools and skills to support private and public institutions.</p></div></div><div className="kh-cp-split"><div className="kh-cp-copy kh-cp-reveal"><p>At Kingshill, we unlock potential and raise builders and reformers.</p><p>Our work sits at the meeting point of personal growth, leadership, and organisational intelligence. We make people see the future — and secure it.</p><Link className="kh-cp-link" to="/training">Explore our programmes <span aria-hidden="true">↗</span></Link></div><aside className="kh-cp-aside kh-cp-reveal" aria-label="Kingshill focus areas">{focus.map(([number, title, copy]) => <div className="kh-cp-aside__row" key={number}><span>{number}</span><div><strong>{title}</strong><p>{copy}</p></div></div>)}</aside></div></div></section>
    <section className="kh-cp-section kh-cp-section--ink"><div className="kh-cp-shell"><div className="kh-cp-section__head kh-cp-reveal"><div className="kh-cp-section__label"><span>02</span><span>What guides us</span></div><div><h2>A clear standard for meaningful work.</h2><p>These values guide everything we do and shape the transformative experiences we create.</p></div></div><div className="kh-cp-card-grid">{values.map(([title, description], index) => <article className="kh-cp-card kh-cp-reveal" key={title}><span className="kh-cp-card__number">{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{description}</p></div><div className="kh-cp-card__foot"><span>Kingshill value</span><span>↗</span></div></article>)}</div></div></section>
    <section className="kh-cp-section kh-cp-section--paper-alt"><div className="kh-cp-shell"><div className="kh-cp-statline kh-cp-reveal"><div><strong>25+</strong><span>Years of excellence</span></div><div><strong>1,000+</strong><span>Graduates</span></div><div><strong>CCC</strong><span>Accredited</span></div></div><blockquote className="kh-cp-quote kh-cp-reveal">“We make you see the future and secure it.”<footer>Kingshill School of Discovery · Since 1999</footer></blockquote></div></section>
    <section className="kh-cp-cta"><div className="kh-cp-shell kh-cp-cta__inner"><div><h2>Make your next move count.</h2><Link className="kh-cp-link" to="/contact">Talk to Kingshill <span aria-hidden="true">↗</span></Link></div><p>Join professionals and organisations building stronger futures through coaching, leadership, and practical intelligence.</p></div></section>
  </CorporatePageFrame>
);
export default About;
