import { Link } from "react-router-dom";
import CorporatePageFrame from "@/components/CorporatePageFrame";

const faculty = [{ name: "Prof. Adebayo Olumide", title: "Director & Lead Coach", credentials: "CCC-MCC, PhD Psychology", specialization: "Leadership & Executive Coaching", experience: "20+ years", bio: "A pioneer in coaching education in Nigeria with extensive experience in leadership development and organisational psychology.", achievements: ["CCC Master Certified Coach", "Published Author", "International Speaker"], courses: ["Executive Coaching", "Leadership Development", "NLP Master Practitioner"] }, { name: "Dr. Kemi Adebisi", title: "Senior Faculty Member", credentials: "CCC-PCC, MSc Counselling Psychology", specialization: "Life Coaching & Personal Development", experience: "15+ years", bio: "Expert in transformational coaching with a passion for empowering individuals to discover their purpose and achieve their goals.", achievements: ["CCC Professional Certified Coach", "Certified NLP Trainer", "Youth Development Expert"], courses: ["Life Coaching Fundamentals", "Personal Development", "Youth Coaching"] }, { name: "Mr. Emeka Okonkwo", title: "Business Coaching Specialist", credentials: "CCC-ACC, MBA Business Administration", specialization: "Business & Career Coaching", experience: "12+ years", bio: "Former corporate executive turned coach, specialising in business development and career transition coaching.", achievements: ["CCC Associate Certified Coach", "Business Consultant", "Career Development Specialist"], courses: ["Business Coaching", "Career Transition", "Entrepreneurship Development"] }];

const Faculty = () => (
  <CorporatePageFrame pageNumber="04" eyebrow="Meet our faculty" title={<>The people behind <em>the practice.</em></>} intro="Learn from Nigeria's most experienced and internationally certified coaching professionals." actionLabel="Book a consultation">
    <section className="kh-cp-section kh-cp-section--ink"><div className="kh-cp-shell"><div className="kh-cp-section__head kh-cp-reveal"><div className="kh-cp-section__label"><span>01</span><span>Faculty directory</span></div><div><h2>Experience that stays useful.</h2><p>Our faculty bring psychology, leadership, business, and lived experience into every room.</p></div></div><div>{faculty.map((member, index) => <article className="kh-cp-profile kh-cp-reveal" key={member.name}><div className="kh-cp-profile__portrait" aria-hidden="true"><span>{String(index + 1).padStart(2, "0")}</span></div><div className="kh-cp-profile__body"><h3>{member.name}</h3><p>{member.bio}</p><div className="kh-cp-profile__meta"><span>{member.title}</span><span>{member.credentials}</span><span>{member.experience}</span></div><div className="kh-cp-profile__links"><span>Focus: {member.specialization}</span><Link to={`/contact?faculty=${encodeURIComponent(member.name)}`}>Contact faculty ↗</Link></div><div className="kh-cp-profile__links"><span>Teaches: {member.courses.join(" · ")}</span><span>Recognised for: {member.achievements.join(" · ")}</span></div></div></article>)}</div></div></section>
    <section className="kh-cp-cta"><div className="kh-cp-shell kh-cp-cta__inner"><div><h2>Learn from the best in the room.</h2><Link className="kh-cp-link" to="/training">View programmes <span aria-hidden="true">↗</span></Link></div><p>Join our internationally accredited programmes and learn from Nigeria&apos;s top coaching professionals.</p></div></section>
  </CorporatePageFrame>
);
export default Faculty;
