import CorporatePageFrame from "@/components/CorporatePageFrame";
import galleryImage1 from "@/assets/img-20250827-wa0012.jpg";
import galleryImage2 from "@/assets/img-20250827-wa0010.jpg";
import galleryImage3 from "@/assets/img-20250827-wa0009.jpg";
import galleryImage4 from "@/assets/img-20250827-wa0023.jpg";
import galleryImage5 from "@/assets/img-20250827-wa0024.jpg";
import galleryImage6 from "@/assets/img-20250827-wa0020-1.jpg";

const gallery = [["Graduation Ceremony 2024", "Celebrating our latest cohort of certified life coaches", galleryImage1, "December 2024 · Lagos"], ["Corporate Training Workshop", "Executive coaching training for business leaders", galleryImage2, "November 2024 · Abuja"], ["Youth Empowerment Program", "Empowering young Nigerians through coaching skills", galleryImage3, "October 2024 · Kano"], ["Business Leaders Forum", "Networking and knowledge sharing among business leaders", galleryImage4, "September 2024 · Port Harcourt"], ["NLP Master Class", "Advanced NLP techniques for experienced practitioners", galleryImage5, "August 2024 · Ibadan"], ["Women in Coaching Summit", "Empowering women coaches across Nigeria", galleryImage6, "July 2024 · Lagos"]];

const Gallery = () => (
  <CorporatePageFrame pageNumber="06" eyebrow="Gallery & stories" title={<>A community in <em>motion.</em></>} intro="A look at the people, rooms, and moments that make the Kingshill learning community real.">
    <section className="kh-cp-section kh-cp-section--paper"><div className="kh-cp-shell"><div className="kh-cp-section__head kh-cp-reveal"><div className="kh-cp-section__label"><span>01</span><span>Video highlights</span></div><div><h2>See the work in the room.</h2><p>From the first question to the final certificate, the work is practical, human, and shared.</p></div></div><div className="kh-cp-resource-grid"><article className="kh-cp-resource kh-cp-resource--feature kh-cp-reveal"><span className="kh-cp-card__number">01 / VIDEO</span><h3>Kingshill School of Discovery Overview</h3><p>Discover our journey and impact across Nigeria.</p><div className="kh-cp-resource__meta"><span>School overview</span><span>5:30</span></div><video className="kh-cp-gallery-video" controls preload="metadata" poster="/IMG-20250827-WA0018.webp"><source src="/VID-20250827-WA0025.mp4" type="video/mp4" />Your browser does not support video playback.</video></article><article className="kh-cp-resource kh-cp-reveal"><span className="kh-cp-card__number">02 / COMMUNITY</span><h3>Student success stories</h3><p>Hear from graduates about the transformation that keeps moving after the classroom.</p><div className="kh-cp-resource__meta"><span>Graduates</span><span>Community</span></div><div className="kh-cp-resource__action">Explore the moments ↘</div></article></div></div></section>
    <section className="kh-cp-section kh-cp-section--ink"><div className="kh-cp-shell"><div className="kh-cp-section__head kh-cp-reveal"><div className="kh-cp-section__label"><span>02</span><span>Photo gallery</span></div><div><h2>People make the picture.</h2><p>Events, workshops, and the everyday work of building better futures together.</p></div></div><div className="kh-cp-gallery">{gallery.map(([title, description, image, meta], index) => <figure className="kh-cp-reveal" key={title}><img src={image} alt={description} loading="lazy" decoding="async" /><figcaption><strong>{String(index + 1).padStart(2, "0")} · {title}</strong><br />{meta}</figcaption></figure>)}<p className="kh-cp-gallery__note">We love keeping in touch with our students after they have graduated and celebrating their success stories and transformative journeys.</p></div></div></section>
    <section className="kh-cp-cta"><div className="kh-cp-shell kh-cp-cta__inner"><div><h2>Bring your next chapter into focus.</h2><a className="kh-cp-link" href="mailto:pg@thecoachingnations.com">Share your story <span aria-hidden="true">↗</span></a></div><p>Follow Kingshill&apos;s community as we keep raising builders and reformers across Nigeria.</p></div></section>
  </CorporatePageFrame>
);
export default Gallery;
