import { Link } from "react-router-dom";
import CorporatePageFrame from "@/components/CorporatePageFrame";

const categories = [{ title: "Free eBooks & Guides", items: [["The Complete Guide to Life Coaching", "A comprehensive introduction to life coaching principles and practices", "PDF Guide · 45 pages · 2,500+ downloads"], ["NLP Fundamentals Workbook", "Practical exercises and techniques for mastering NLP basics", "Interactive workbook · 62 pages · 1,800+ downloads"], ["Youth Coaching Strategies", "Effective approaches for coaching young people and teenagers", "Strategy guide · 38 pages · 1,200+ downloads"]] }, { title: "Video Tutorials & Webinars", items: [["Introduction to Coaching Skills", "Learn the foundational skills every coach needs to succeed", "Video series · 2.5 hours · 5,000+ views"], ["Building Your Coaching Practice", "Step-by-step guide to starting and growing your coaching business", "Masterclass · 90 minutes · 3,200+ views"], ["Advanced NLP Techniques", "A deep dive into advanced NLP methods for experienced practitioners", "Workshop recording · 3 hours · 2,800+ views"]] }, { title: "Templates & Tools", items: [["Coaching Session Planner", "Structured templates for planning effective coaching sessions", "Template pack · 12 templates · 4,200+ downloads"], ["Client Assessment Forms", "Professional forms for initial client consultations and ongoing assessments", "Form collection · 8 forms · 3,500+ downloads"], ["Goal Setting Worksheets", "Interactive worksheets to help clients set and achieve their goals", "Worksheet set · 15 worksheets · 5,100+ downloads"]] }];
const requestHref = (title: string) => `mailto:PG@kingshillcoachingacademy.org?subject=${encodeURIComponent(`Resource request: ${title}`)}`;

const Resources = () => (
  <CorporatePageFrame pageNumber="05" eyebrow="Resources & tools" title={<>Keep the work <em>moving.</em></>} intro="Access our library of free guides, templates, and training materials to enhance your coaching journey." actionLabel="Ask for a resource">
    <section className="kh-cp-section kh-cp-section--paper"><div className="kh-cp-shell"><div className="kh-cp-section__head kh-cp-reveal"><div className="kh-cp-section__label"><span>01</span><span>Featured resources</span></div><div><h2>Useful by design.</h2><p>Start with the resources our community returns to most.</p></div></div><div className="kh-cp-resource-grid"><article className="kh-cp-resource kh-cp-resource--feature kh-cp-reveal"><span className="kh-cp-card__number">01 / PREMIUM GUIDE</span><h3>Coaching Excellence Handbook</h3><p>Our most comprehensive resource covering all aspects of professional coaching.</p><div className="kh-cp-resource__meta"><span>120 pages</span><span>4.9 / 5</span><span>450 reviews</span></div><a className="kh-cp-resource__action" href={requestHref("Coaching Excellence Handbook")}>Download free ↗</a></article><article className="kh-cp-resource kh-cp-reveal"><span className="kh-cp-card__number">02 / LEARNING PATH</span><h3>Master Coach Certification Path</h3><p>A complete roadmap to achieving ICF Master Certified Coach status.</p><div className="kh-cp-resource__meta"><span>12 modules</span><span>4.8 / 5</span><span>280 reviews</span></div><a className="kh-cp-resource__action" href={requestHref("Master Coach Certification Path")}>Request guide ↗</a></article></div></div></section>
    <section className="kh-cp-section kh-cp-section--ink"><div className="kh-cp-shell"><div className="kh-cp-section__head kh-cp-reveal"><div className="kh-cp-section__label"><span>02</span><span>Resource library</span></div><div><h2>Pick up where you are.</h2><p>Guides for the first question, tools for the next step, and material for the long practice.</p></div></div>{categories.map((category) => <div className="kh-cp-resource-group" key={category.title}><div className="kh-cp-section__label"><span>{category.title}</span></div><div className="kh-cp-card-grid">{category.items.map(([title, description, meta], index) => <article className="kh-cp-card kh-cp-reveal" key={title}><span className="kh-cp-card__number">{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{description}</p></div><div className="kh-cp-card__foot"><span>{meta}</span><a href={requestHref(title)}>Get resource ↗</a></div></article>)}</div></div>)}</div></section>
    <section className="kh-cp-cta"><div className="kh-cp-shell kh-cp-cta__inner"><div><h2>Need more personalised support?</h2><Link className="kh-cp-link" to="/training">Explore programmes <span aria-hidden="true">↗</span></Link></div><p>While these resources are useful for self-learning, nothing beats personalised training and mentorship.</p></div></section>
  </CorporatePageFrame>
);
export default Resources;
