import { Link } from "react-router-dom";
import CorporatePageFrame from "@/components/CorporatePageFrame";

const programmes = [{ title: "Life Coaching Certification", description: "Our flagship CCC-accredited programme with 20+ coaching designations that transforms lives and careers.", features: ["CCC accredited", "20+ designations"] }, { title: "Transitional Youth Coaching Program", description: "Specialised training for coaching young professionals and students.", features: ["Youth focused", "3 months"] }, { title: "Youth Entrepreneurship Program (YEP)", description: "Empowering young entrepreneurs with business coaching and mentorship.", features: ["Business coaching", "4 months"] }, { title: "Ministry Coaching Program (MCP)", description: "Specialised coaching for religious and ministry leaders.", features: ["Ministry focus", "5 months"] }];
const designations = ["Personal Coaching", "Relationship & Marital Coaching", "Business & Strategy Coaching", "Investment & Finance Coaching", "Spiritual Intelligence Coaching", "Ministry Coaching", "Teenage Coaching", "Youth Development Coaching", "Sex and Sexuality Coaching", "Mindshift Coaching", "Transformational Coaching", "Corporate & Executive Coaching", "Mental Health Coaching", "Lifestyle Health Coaching", "Communication Coaching", "Sales Coaching", "Peak Performance Coaching", "Leadership Coaching", "Management Coaching", "Human Design Systems Coaching"];

const Training = () => (
  <CorporatePageFrame pageNumber="03" eyebrow="Training programmes" title={<>Learn to move <em>people forward.</em></>} intro="In addition to our life coaching core certification, we offer a range of specialist programmes with 20+ coaching designations you can study alongside or on their own.">
    <section className="kh-cp-section kh-cp-section--paper"><div className="kh-cp-shell"><div className="kh-cp-section__head kh-cp-reveal"><div className="kh-cp-section__label"><span>01</span><span>Choose your path</span></div><div><h2>Training with range.</h2><p>Build a practice around the people and problems you care about most.</p></div></div><div className="kh-cp-card-grid">{programmes.map((program, index) => <article className="kh-cp-card kh-cp-reveal" key={program.title}><span className="kh-cp-card__number">{String(index + 1).padStart(2, "0")}{index === 0 ? " / FEATURED" : ""}</span><div><h3>{program.title}</h3><p>{program.description}</p></div><div className="kh-cp-card__foot"><span>{program.features.join(" · ")}</span><Link to={`/contact?programme=${encodeURIComponent(program.title)}`}>Learn more ↗</Link></div></article>)}</div></div></section>
    <section className="kh-cp-section kh-cp-section--ink"><div className="kh-cp-shell"><div className="kh-cp-section__head kh-cp-reveal"><div className="kh-cp-section__label"><span>02</span><span>20+ specialisations</span></div><div><h2>Find the work that fits you.</h2><p>Our Life Coaching Certification programme lets you focus your learning and serve specific client needs.</p></div></div><div className="kh-cp-index-list">{designations.map((designation, index) => <span className="kh-cp-reveal" key={designation}><strong>{String(index + 1).padStart(2, "0")}</strong>{designation}</span>)}</div></div></section>
    <section className="kh-cp-section kh-cp-section--teal"><div className="kh-cp-shell kh-cp-split"><div className="kh-cp-copy kh-cp-reveal"><p>Study with people who understand the work.</p><p>Our approach is practical, focused, and designed to turn knowledge into confident action — in your own life, in your clients&apos; lives, and in organisations.</p></div><aside className="kh-cp-aside kh-cp-reveal"><div className="kh-cp-aside__row"><span>01</span><div><strong>CCC accredited</strong><p>Professional recognition for your learning journey.</p></div></div><div className="kh-cp-aside__row"><span>02</span><div><strong>Mentorship built in</strong><p>Guidance that continues beyond the classroom.</p></div></div><div className="kh-cp-aside__row"><span>03</span><div><strong>Practical training</strong><p>Tools you can use from your first session.</p></div></div></aside></div></section>
    <section className="kh-cp-cta"><div className="kh-cp-shell kh-cp-cta__inner"><div><h2>Your next chapter starts here.</h2><Link className="kh-cp-link" to="/contact">Ask about enrolment <span aria-hidden="true">↗</span></Link></div><p>Contact the Kingshill team for programme dates, fees, and the right path for your goals.</p></div></section>
  </CorporatePageFrame>
);
export default Training;
